// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/entry.dart';
import 'data/models/ritual.dart';
import 'data/models/tree.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 980722598120104709),
    name: 'Entry',
    lastPropertyId: const obx_int.IdUid(23, 8840600702752248780),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 269502239998818654),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4422281124207185487),
        name: 'createdAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(1, 3928695469656222066),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 353915068729339971),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3708880826332420230),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7375884822086644768),
        name: 'mediaPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6053545043161884039),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 226156736396886711),
        name: 'context',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5791614792974334851),
        name: 'mood',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3041290548098779867),
        name: 'tags',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5610169781178833264),
        name: 'isReleased',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1952791767777103688),
        name: 'isDeleted',
        type: 1,
        flags: 8,
        indexId: const obx_int.IdUid(2, 5746525490482150823),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 95477390163426456),
        name: 'deletedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4412152896935047327),
        name: 'detectedTheme',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4459816486174533736),
        name: 'connectionIds',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4010109162980093924),
        name: 'sentimentScore',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 6242043607225809772),
        name: 'lastAnalyzedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 4822441182230169529),
        name: 'connectedIds',
        type: 27,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 7049565280661572356),
        name: 'capsuleUnlockDate',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(3, 5594065671377155778),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 6989500767525477215),
        name: 'transcription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 5287589025787022643),
        name: 'syncUUID',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 2626856446788976910),
        name: 'modifiedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 3618374170569244160),
        name: 'deviceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 8840600702752248780),
        name: 'manualLinkIds',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3362048758403623883),
    name: 'Tree',
    lastPropertyId: const obx_int.IdUid(5, 5939974100987378786),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5290125901850262022),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1715661857793943423),
        name: 'year',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4617615204353589173),
        name: 'entryCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 404156755750246248),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5939974100987378786),
        name: 'stateIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8814026308694728405),
    name: 'Ritual',
    lastPropertyId: const obx_int.IdUid(11, 786135456654185868),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9126252907033325446),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1024230205657674547),
        name: 'uuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5723073435690232525),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 496945034011078349),
        name: 'signature',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3643181829478333684),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7552542947224669242),
        name: 'cadenceDays',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7014604637639458632),
        name: 'preferredHour',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6648556305350325062),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6459583029169323667),
        name: 'lastObservedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6610698839710776274),
        name: 'nextDueAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 786135456654185868),
        name: 'occurrenceCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 8814026308694728405),
    lastIndexId: const obx_int.IdUid(3, 5594065671377155778),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Entry: obx_int.EntityDefinition<Entry>(
      model: _entities[0],
      toOneRelations: (Entry object) => [],
      toManyRelations: (Entry object) => {},
      getId: (Entry object) => object.id,
      setId: (Entry object, int id) {
        object.id = id;
      },
      objectToFB: (Entry object, fb.Builder fbb) {
        final textOffset = object.text == null
            ? null
            : fbb.writeString(object.text!);
        final mediaPathOffset = object.mediaPath == null
            ? null
            : fbb.writeString(object.mediaPath!);
        final titleOffset = object.title == null
            ? null
            : fbb.writeString(object.title!);
        final contextOffset = object.context == null
            ? null
            : fbb.writeString(object.context!);
        final moodOffset = object.mood == null
            ? null
            : fbb.writeString(object.mood!);
        final tagsOffset = object.tags == null
            ? null
            : fbb.writeString(object.tags!);
        final detectedThemeOffset = object.detectedTheme == null
            ? null
            : fbb.writeString(object.detectedTheme!);
        final connectionIdsOffset = object.connectionIds == null
            ? null
            : fbb.writeString(object.connectionIds!);
        final connectedIdsOffset = fbb.writeListInt64(object.connectedIds);
        final transcriptionOffset = object.transcription == null
            ? null
            : fbb.writeString(object.transcription!);
        final syncUUIDOffset = object.syncUUID == null
            ? null
            : fbb.writeString(object.syncUUID!);
        final deviceIdOffset = object.deviceId == null
            ? null
            : fbb.writeString(object.deviceId!);
        final manualLinkIdsOffset = object.manualLinkIds == null
            ? null
            : fbb.writeString(object.manualLinkIds!);
        fbb.startTable(24);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(2, object.typeIndex);
        fbb.addOffset(3, textOffset);
        fbb.addOffset(4, mediaPathOffset);
        fbb.addOffset(5, titleOffset);
        fbb.addOffset(6, contextOffset);
        fbb.addOffset(7, moodOffset);
        fbb.addOffset(8, tagsOffset);
        fbb.addBool(9, object.isReleased);
        fbb.addBool(10, object.isDeleted);
        fbb.addInt64(11, object.deletedAt?.millisecondsSinceEpoch);
        fbb.addOffset(12, detectedThemeOffset);
        fbb.addOffset(13, connectionIdsOffset);
        fbb.addFloat64(14, object.sentimentScore);
        fbb.addInt64(15, object.lastAnalyzedAt?.millisecondsSinceEpoch);
        fbb.addOffset(16, connectedIdsOffset);
        fbb.addInt64(17, object.capsuleUnlockDate?.millisecondsSinceEpoch);
        fbb.addOffset(18, transcriptionOffset);
        fbb.addOffset(19, syncUUIDOffset);
        fbb.addInt64(20, object.modifiedAt?.millisecondsSinceEpoch);
        fbb.addOffset(21, deviceIdOffset);
        fbb.addOffset(22, manualLinkIdsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final deletedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final lastAnalyzedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final capsuleUnlockDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          38,
        );
        final modifiedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          44,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final typeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final mediaPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final contextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final moodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final tagsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final isReleasedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final deletedAtParam = deletedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(deletedAtValue);
        final detectedThemeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final connectionIdsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final manualLinkIdsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final sentimentScoreParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final lastAnalyzedAtParam = lastAnalyzedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastAnalyzedAtValue);
        final capsuleUnlockDateParam = capsuleUnlockDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(capsuleUnlockDateValue);
        final transcriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final syncUUIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 42);
        final modifiedAtParam = modifiedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(modifiedAtValue);
        final deviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final object =
            Entry(
                id: idParam,
                createdAt: createdAtParam,
                typeIndex: typeIndexParam,
                text: textParam,
                mediaPath: mediaPathParam,
                title: titleParam,
                context: contextParam,
                mood: moodParam,
                tags: tagsParam,
                isReleased: isReleasedParam,
                isDeleted: isDeletedParam,
                deletedAt: deletedAtParam,
                detectedTheme: detectedThemeParam,
                connectionIds: connectionIdsParam,
                manualLinkIds: manualLinkIdsParam,
                sentimentScore: sentimentScoreParam,
                lastAnalyzedAt: lastAnalyzedAtParam,
                capsuleUnlockDate: capsuleUnlockDateParam,
                transcription: transcriptionParam,
                syncUUID: syncUUIDParam,
                modifiedAt: modifiedAtParam,
                deviceId: deviceIdParam,
              )
              ..connectedIds = const fb.ListReader<int>(
                fb.Int64Reader(),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 36, []);

        return object;
      },
    ),
    Tree: obx_int.EntityDefinition<Tree>(
      model: _entities[1],
      toOneRelations: (Tree object) => [],
      toManyRelations: (Tree object) => {},
      getId: (Tree object) => object.id,
      setId: (Tree object, int id) {
        object.id = id;
      },
      objectToFB: (Tree object, fb.Builder fbb) {
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.year);
        fbb.addInt64(2, object.entryCount);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.stateIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final yearParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final entryCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final stateIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = Tree(
          id: idParam,
          year: yearParam,
          entryCount: entryCountParam,
          createdAt: createdAtParam,
          stateIndex: stateIndexParam,
        );

        return object;
      },
    ),
    Ritual: obx_int.EntityDefinition<Ritual>(
      model: _entities[2],
      toOneRelations: (Ritual object) => [],
      toManyRelations: (Ritual object) => {},
      getId: (Ritual object) => object.id,
      setId: (Ritual object, int id) {
        object.id = id;
      },
      objectToFB: (Ritual object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final signatureOffset = fbb.writeString(object.signature);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, signatureOffset);
        fbb.addInt64(4, object.statusIndex);
        fbb.addInt64(5, object.cadenceDays);
        fbb.addInt64(6, object.preferredHour);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.lastObservedAt?.millisecondsSinceEpoch);
        fbb.addInt64(9, object.nextDueAt?.millisecondsSinceEpoch);
        fbb.addInt64(10, object.occurrenceCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastObservedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final nextDueAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final signatureParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final cadenceDaysParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final preferredHourParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final lastObservedAtParam = lastObservedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastObservedAtValue);
        final nextDueAtParam = nextDueAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(nextDueAtValue);
        final occurrenceCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = Ritual(
          id: idParam,
          uuid: uuidParam,
          name: nameParam,
          signature: signatureParam,
          statusIndex: statusIndexParam,
          cadenceDays: cadenceDaysParam,
          preferredHour: preferredHourParam,
          createdAt: createdAtParam,
          lastObservedAt: lastObservedAtParam,
          nextDueAt: nextDueAtParam,
          occurrenceCount: occurrenceCountParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Entry] entity fields to define ObjectBox queries.
class Entry_ {
  /// See [Entry.id].
  static final id = obx.QueryIntegerProperty<Entry>(_entities[0].properties[0]);

  /// See [Entry.createdAt].
  static final createdAt = obx.QueryDateProperty<Entry>(
    _entities[0].properties[1],
  );

  /// See [Entry.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<Entry>(
    _entities[0].properties[2],
  );

  /// See [Entry.text].
  static final text = obx.QueryStringProperty<Entry>(
    _entities[0].properties[3],
  );

  /// See [Entry.mediaPath].
  static final mediaPath = obx.QueryStringProperty<Entry>(
    _entities[0].properties[4],
  );

  /// See [Entry.title].
  static final title = obx.QueryStringProperty<Entry>(
    _entities[0].properties[5],
  );

  /// See [Entry.context].
  static final context = obx.QueryStringProperty<Entry>(
    _entities[0].properties[6],
  );

  /// See [Entry.mood].
  static final mood = obx.QueryStringProperty<Entry>(
    _entities[0].properties[7],
  );

  /// See [Entry.tags].
  static final tags = obx.QueryStringProperty<Entry>(
    _entities[0].properties[8],
  );

  /// See [Entry.isReleased].
  static final isReleased = obx.QueryBooleanProperty<Entry>(
    _entities[0].properties[9],
  );

  /// See [Entry.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<Entry>(
    _entities[0].properties[10],
  );

  /// See [Entry.deletedAt].
  static final deletedAt = obx.QueryDateProperty<Entry>(
    _entities[0].properties[11],
  );

  /// See [Entry.detectedTheme].
  static final detectedTheme = obx.QueryStringProperty<Entry>(
    _entities[0].properties[12],
  );

  /// See [Entry.connectionIds].
  static final connectionIds = obx.QueryStringProperty<Entry>(
    _entities[0].properties[13],
  );

  /// See [Entry.sentimentScore].
  static final sentimentScore = obx.QueryDoubleProperty<Entry>(
    _entities[0].properties[14],
  );

  /// See [Entry.lastAnalyzedAt].
  static final lastAnalyzedAt = obx.QueryDateProperty<Entry>(
    _entities[0].properties[15],
  );

  /// See [Entry.connectedIds].
  static final connectedIds = obx.QueryIntegerVectorProperty<Entry>(
    _entities[0].properties[16],
  );

  /// See [Entry.capsuleUnlockDate].
  static final capsuleUnlockDate = obx.QueryDateProperty<Entry>(
    _entities[0].properties[17],
  );

  /// See [Entry.transcription].
  static final transcription = obx.QueryStringProperty<Entry>(
    _entities[0].properties[18],
  );

  /// See [Entry.syncUUID].
  static final syncUUID = obx.QueryStringProperty<Entry>(
    _entities[0].properties[19],
  );

  /// See [Entry.modifiedAt].
  static final modifiedAt = obx.QueryDateProperty<Entry>(
    _entities[0].properties[20],
  );

  /// See [Entry.deviceId].
  static final deviceId = obx.QueryStringProperty<Entry>(
    _entities[0].properties[21],
  );

  /// See [Entry.manualLinkIds].
  static final manualLinkIds = obx.QueryStringProperty<Entry>(
    _entities[0].properties[22],
  );
}

/// [Tree] entity fields to define ObjectBox queries.
class Tree_ {
  /// See [Tree.id].
  static final id = obx.QueryIntegerProperty<Tree>(_entities[1].properties[0]);

  /// See [Tree.year].
  static final year = obx.QueryIntegerProperty<Tree>(
    _entities[1].properties[1],
  );

  /// See [Tree.entryCount].
  static final entryCount = obx.QueryIntegerProperty<Tree>(
    _entities[1].properties[2],
  );

  /// See [Tree.createdAt].
  static final createdAt = obx.QueryDateProperty<Tree>(
    _entities[1].properties[3],
  );

  /// See [Tree.stateIndex].
  static final stateIndex = obx.QueryIntegerProperty<Tree>(
    _entities[1].properties[4],
  );
}

/// [Ritual] entity fields to define ObjectBox queries.
class Ritual_ {
  /// See [Ritual.id].
  static final id = obx.QueryIntegerProperty<Ritual>(
    _entities[2].properties[0],
  );

  /// See [Ritual.uuid].
  static final uuid = obx.QueryStringProperty<Ritual>(
    _entities[2].properties[1],
  );

  /// See [Ritual.name].
  static final name = obx.QueryStringProperty<Ritual>(
    _entities[2].properties[2],
  );

  /// See [Ritual.signature].
  static final signature = obx.QueryStringProperty<Ritual>(
    _entities[2].properties[3],
  );

  /// See [Ritual.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<Ritual>(
    _entities[2].properties[4],
  );

  /// See [Ritual.cadenceDays].
  static final cadenceDays = obx.QueryIntegerProperty<Ritual>(
    _entities[2].properties[5],
  );

  /// See [Ritual.preferredHour].
  static final preferredHour = obx.QueryIntegerProperty<Ritual>(
    _entities[2].properties[6],
  );

  /// See [Ritual.createdAt].
  static final createdAt = obx.QueryDateProperty<Ritual>(
    _entities[2].properties[7],
  );

  /// See [Ritual.lastObservedAt].
  static final lastObservedAt = obx.QueryDateProperty<Ritual>(
    _entities[2].properties[8],
  );

  /// See [Ritual.nextDueAt].
  static final nextDueAt = obx.QueryDateProperty<Ritual>(
    _entities[2].properties[9],
  );

  /// See [Ritual.occurrenceCount].
  static final occurrenceCount = obx.QueryIntegerProperty<Ritual>(
    _entities[2].properties[10],
  );
}
