import 'memory_theme.dart';

/// Types of smart suggestions the AI can generate
enum SuggestionType {
  /// Based on time of day or day of week patterns
  timeAware,

  /// Based on detected patterns in user's entries
  patternBased,

  /// Suggesting under-represented themes
  gapFilling,

  /// Anniversary of a past memory
  anniversary,
}

/// A smart suggestion generated by the AI engine
///
/// Suggestions are personalized based on the user's entry history,
/// detected patterns, and identified gaps in their memory themes.
class SmartSuggestion {
  /// The suggestion text to display
  final String text;

  /// Type of suggestion
  final SuggestionType type;

  /// Why this suggestion was generated
  final String reason;

  /// Associated theme (if gap-filling)
  final MemoryTheme? targetTheme;

  /// Related entry ID (if anniversary)
  final int? relatedEntryId;

  /// Confidence score (0.0 to 1.0)
  final double confidence;

  const SmartSuggestion({
    required this.text,
    required this.type,
    required this.reason,
    this.targetTheme,
    this.relatedEntryId,
    this.confidence = 0.5,
  });

  /// Human-readable type label
  String get typeLabel {
    switch (type) {
      case SuggestionType.timeAware:
        return 'Time-based';
      case SuggestionType.patternBased:
        return 'Based on your patterns';
      case SuggestionType.gapFilling:
        return 'Explore new themes';
      case SuggestionType.anniversary:
        return 'Memory anniversary';
    }
  }
}

/// Analysis of theme gaps in user's entries
class ThemeGap {
  /// The under-represented theme
  final MemoryTheme theme;

  /// Percentage of entries with this theme (0.0 to 1.0)
  final double percentage;

  /// Days since last entry with this theme
  final int daysSinceLastEntry;

  const ThemeGap({
    required this.theme,
    required this.percentage,
    required this.daysSinceLastEntry,
  });

  /// Whether this is a significant gap
  bool get isSignificant => percentage < 0.05 && daysSinceLastEntry > 14;
}
